### ISSUE TITLE
Window is blank right after start

### ISSUE THREAD

**Issue by melix99** [actuate-rs/actuate#76]
I tried running the `counter` example on my system (Fedora Silverblue 41), but on first start the window is completely blank, until I click on one of the two buttons to change the state of the counter:

[Screencast From 2024-11-24 15-11-44.webm](https://github.com/user-attachments/assets/4bcc80c3-cb7d-496b-9204-1b6fc8f84e09)

I tired to debug this issue a bit and I noticed that, on start, the app got two `RedrawRequested` events. So, I tried to comment [this line](https://github.com/actuate-rs/actuate/blob/b2783f068a92cf0e70a97b61a1148cab22d43f5a/src/ui/view/window.rs#L294) and the issue got away (but obviously the window stopped redrawing).

Unfortunately I don't know how the debug this further.

**Comment by matthunz** [comment]
Appreciate the insight! This definitely looks like a difference on Linux (as you mention maybe it has something to do with the extra `RedrawRequested`?)

**Comment by matthunz** [comment]
Potentially related https://github.com/actuate-rs/actuate/issues/78

The current render logic may actually be rendering a blank `Scene` the second redraw 🤔 a new element tree should fix this by changing the paint pass

**Comment by matthunz** [comment]
Closed in favor of https://github.com/actuate-rs/actuate/pull/79
