### ISSUE TITLE
Counter example is behaving strangely

### ISSUE THREAD

**Issue by melix99** [actuate-rs/actuate#77]
It seems that something is wrong in the counter example: when I click e.g. the up button a few times, the counter goes up just fine, but if I click the down button once, the counter still goes up. If I click it again, then the counter actually goes down.

[Screencast From 2024-11-24 15-54-51.webm](https://github.com/user-attachments/assets/8aec7be1-41d7-4ae2-b5fa-6e4b765563f2)

I initially thought it was somehow caused by #76, so I added some `println` to make sure that it's not just a rendering error.

**Comment by matthunz** [comment]
Hmm thanks for catching this!

I can't seem to reproduce this exact issue, but I have noticed strange click behavior. I'm hoping this is due to the hacky current implementation here: https://github.com/actuate-rs/actuate/blob/b2783f068a92cf0e70a97b61a1148cab22d43f5a/src/ui/view/mod.rs#L254

I think ideally the click target should be handled globally by the window 🤔

**Comment by matthunz** [comment]
Potentially related https://github.com/actuate-rs/actuate/issues/78

**Comment by DasLixou** [comment]
I have encountered the same thing, I think it is somehow rendering while two adds are still in queue, then they get processed but render already happened so we do nothing and on decrementing, we are only 1 above, not 2.

**Comment by matthunz** [comment]
I think you were exactly right @DasLixou 🤔 drawing to the `Scene` directly from the `Compose` tree looks like it was causing that, with the only way I could think around it being a lower-level tree.

For now I decided against the custom backend, I think what's most important is to hammer down the core declarative programming tools.

I added some more thoughts here: https://github.com/actuate-rs/actuate/issues/78
